services:
  java-price-service:
    image: eclipse-temurin:21-jdk
    working_dir: /app
    volumes:
      - ./java-price-service:/app
    command: sh -c "javac src/com/javago/pricing/PriceService.java && java -cp src com.javago.pricing.PriceService"
    ports:
      - "8081:8081"

  python-analysis-service:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./python-analysis-service:/app
    command: python app.py
    ports:
      - "8082:8082"
